import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/feature/darkMode/themeProvider";
import Header from "@/components/feature/header/header";

import { cookies } from "next/headers";
import { UserProvider } from "@/components/feature/provider/UserProvider";
import { verifyJwtServer } from "@/lib/token/jwt.server";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const token = cookieStore.get("accessToken")?.value ?? null;

	let initialUser = null;
	if (token) {
		try {
			const payload = await verifyJwtServer(token, process.env.JWT_SECRET!);
			initialUser = { id: payload.id, username: payload.username };
		} catch (e) {
			initialUser = null;
		}
	}

	return (
		<html lang="ja" suppressHydrationWarning>
			<body>
				<UserProvider initialUser={initialUser}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<Header />
						<main className="mt-12">{children}</main>
					</ThemeProvider>
				</UserProvider>
			</body>
		</html>
	);
}
