// This file is auto-generated by scripts/generate-product-update-markdown.ts.
// Do not edit manually.

export const PRODUCT_UPDATE_DETAILS = {
	"post-realtime-update":
		"スレッドを開いたままにしておくと、新しいポストを自動で取り込み、画面を更新するようにしました。\n\n## 技術構成\n\nCloudflare の `Durable Objects` と `WebSockets` を使って実装しています。\n",
	"thread-search-page":
		"## 検索ページを追加しました\n\nヘッダーの検索アイコンから検索ページへ移動でき、スレッドを横断して探せるようになりました。\n\n## リアルタイムで絞り込めます\n\n入力中の検索語にあわせて、その場で結果が更新されます。\n\n## 一致箇所を見つけやすくしました\n\n検索語は結果一覧のタイトル内でハイライト表示されるため、どのスレッドが一致しているのかを見分けやすくしています。\n",
} satisfies Record<string, string>;
