import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const INPUT_DIR = path.join(process.cwd(), "src/content/product-updates");
const OUTPUT_FILE = path.join(INPUT_DIR, "generated.ts");

const run = async () => {
	const entries = await readdir(INPUT_DIR, { withFileTypes: true });
	const markdownFiles = entries
		.filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
		.map((entry) => entry.name)
		.sort();

	const detailEntries = await Promise.all(
		markdownFiles.map(async (fileName) => {
			const slug = fileName.slice(0, -3);
			const content = await readFile(path.join(INPUT_DIR, fileName), "utf8");

			return [slug, content] as const;
		}),
	);

	const objectLiteral = detailEntries
		.map(
			([slug, content]) =>
				`\t${JSON.stringify(slug)}: ${JSON.stringify(content)},`,
		)
		.join("\n");

	const fileContent = `// This file is auto-generated by scripts/generate-product-update-markdown.ts.
// Do not edit manually.

export const PRODUCT_UPDATE_DETAILS = {
${objectLiteral}
} satisfies Record<string, string>;
`;

	await mkdir(INPUT_DIR, { recursive: true });
	await writeFile(OUTPUT_FILE, fileContent, "utf8");
};

await run();
